### ISSUE TITLE
On the result for LTCC dataset

### ISSUE THREAD

**Issue by 1292224662** [QizaoWang/FIRe-CCReID#1]
Dear authors, I find this work very interesting and easy to follow. However, when I try to reproduce the results for LTCC dataset, I get a lower result compared to those in the paper.

I didn't modify the origin code in this repo and my command is strictly follow the command in the readme:

```
python main.py --gpu_devices 0 --dataset ltcc --dataset_root DATASET_ROOT --dataset_filename LTCC-reID --save_dir SAVE_DIR --save_checkpoint
```

My result were:

```
==> Best mAP 38.5886%, achieved at epoch 45
==> Best Rank-1 73.4280%, achieved at epoch 75
==> Best mAP_2 17.8189%, achieved at epoch 70
==> Best Rank-1_2 40.3061%, achieved at epoch 65
```

Though they are almost aligned with those in the original paper, there are still slight differences between them. For example, in CC setting, the rank-1/mAP is 40.3/17.8, while that in the original paper is 44.6/19.1.

I wonder is there any advice on how to better reproduce the results in the paper? Looking forward to your reply.

**Comment by QizaoWang** [comment]
Thank you for being interested in our work. As mentioned in our guide, increasing the $eps$ value on difficult datasets like LTCC may reduce noise and lead to slightly better performance. Please feel free to try. Furthermore, it is normal for there to be slight variations in the results across different devices.
