### ISSUE TITLE
The results after training differ from those reported in the paper

### ISSUE THREAD

**Issue by Crush52-sys** [QizaoWang/FIRe-CCReID#2]
Hello, after following the training commands in the readme, I obtained the following results:
For the LTCC dataset: Best mAP is 17.6509%, and Best Rank-1 is 38.7755%.
For the PRCC dataset: Best mAP is 58.4294%, and Best Rank-1 is 58.9896%.

Could you kindly advise if there are any parameters that need adjustment?

**Comment by QizaoWang** [comment]
Thank you for your interest in our work! The results reported in our paper were achieved without performing grid tuning on the hyperparameters. Adjusting hyperparameters, such as --eps and --FAR_weight, for different datasets may lead to improved performance, while you can achieve similar results with the released code. 
Variations in training results could also be influenced by factors like randomness and differences in hardware. For reference, the experiments in our paper were conducted on NVIDIA GeForce GTX 1080 Ti. Additionally, we recommend trying larger datasets, such as DeepChange and LaST, which tend to produce more stable results.
